name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint
