name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testnode16:
    name: Test Node 16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint

  testnode14:
    name: Test Node 14
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint

  testnode12:
    name: Test Node 12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node v12
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 12

      - name: Install dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint
